name: docker-build-workflow
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: null
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create  artifact dist folder
        run: |
          mkdir dist
          sudo apt update
          sudo apt install tar gzip build-essential
          ls
          cd  dist
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        working-directory: 03-app-dotnet
        run: |
         docker build . --file Dockerfile --tag my-app-dotnet:$(date +%s)
         docker save my-app-dotnet > my-image.tar
         ls
         gzip my-image.tar
         ls -lh my-image.tar.gz
         pwd
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           push: true
#           context: 03-app-dotnet
#           dockerfile: my-image.tar.gz
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-image:newtarfile
      - name: upload all aritifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-image
          path: /home/runner/work/github-actions-course/github-actions-course/03-app-dotnet/my-image.tar.gz
#       - name: tar file
#         uses: nxtlvlsoftware/tar-ops-action@v1
#         with:
#           operation: compress
#           files: dist
#           outPath: ./dist.tgz
#       - name: validate all input
#         run: |
#           pwd
#           ls 
#           cd my-image
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-image
#       - name: validate output
#         run: |
#           pwd
#           ls
#       - name: tar folder
#         uses: nxtlvlsoftware/tar-ops-action@v1
#         with:
#           operation: compress
#           files: dist
#           outPath: ./dist.tgz
