name: docker-build-workflow
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: null
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create  artifact dist folder
        run: |
          mkdir dist
          sudo apt update
          sudo apt install tar gzip build-essential
          ls
          cd  dist
      - name: Build the Docker image
        working-directory: 03-app-dotnet
        run: docker build . --file Dockerfile --tag my-app-dotnet:$(date +%s)
      - name: upload all aritifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
